name: CI
on:
  push:
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'master'
      - 'release-[0-9]+.[0-9]+'
    paths-ignore:
      - 'runtime/doc/*'

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  unixish:
    name: ${{ matrix.runner }} ${{ matrix.flavor }} (cc=${{ matrix.cc }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: clang
            runner: macos-10.15
            os: osx
          - cc: clang
            runner: macos-11.0
            os: osx
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 45
    if: github.event.pull_request.draft == false
    env:
      CC: ${{ matrix.cc }}
      CI_OS_NAME: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup common environment variables
        run: ./.github/workflows/env.sh ${{ matrix.flavor }}

      - name: Install brew packages
        if: matrix.os == 'osx'
        run: |
          brew update --quiet
          brew install automake ccache cpanminus ninja
