name: lintcommit_dummy
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'release-[0-9]+.[0-9]+'
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - run: echo "success"
