name: "Request reviews"
on:
  pull_request_target:
    types: [labeled]
  workflow_run:
    workflows: [Pull Request Labeler]
    types: [completed]
jobs:
  request-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Output Run Env
        run: printenv
        shell: bash
    
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/github-script@v5
        with:
          script: |
            const reviewers = []

            const issues = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })

            const pr = context.issue.number || issues.data[0].number

            const { data: { labels } } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr
            })
            const label_names = labels.map(label => label.name)
