name: "Request reviews"
on:
  pull_request_target:
    types: [labeled, ready_for_review]
jobs:
  request-reviewer:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: wget https://raw.githubusercontent.com/neovim/neovim/master/ci/reviews.js
      - name: 'Request reviewers'
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./reviews.js')
            await script({github, context})
