name: "Request reviews"
on:
  pull_request_target:
    types: [labeled]
  workflow_run:
    workflows: [Pull Request Labeler]
    types: [completed]
jobs:
  request-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            pr = context.issue.number || context.payload.workflow_run.pull_requests[0].number
            console.log(pr)
