name: "Request reviews"
on:
  pull_request_target:
    types: [labeled]
  workflow_run:
    workflows: [Pull Request Labeler]
    types: [completed]
jobs:
  request-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const reviewers = []

            // The number of the pull request that triggered this run. If label
            // was added manually by a person the number will be stored in current
            // context, otherwise the number will be stored in the payload.
            const pr_number = context.issue.number || context.payload.workflow_run.pull_requests[0].number

            const pr_data = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            })
            const labels = pr_data.data.labels.map(e => e.name)

            if (labels.includes('api')) {
              reviewers.push("bfredl")
              reviewers.push("gpanders")
              reviewers.push("muniter")
            }

            if (labels.includes('ci')) {
              reviewers.push("jamessan")
            }

            if (labels.includes('diagnostic')) {
              reviewers.push("gpanders")
            }

            if (labels.includes('distribution')) {
              reviewers.push("jamessan")
            }

            if (labels.includes('documentation')) {
              reviewers.push("clason")
            }

            if (labels.includes('extmarks')) {
              reviewers.push("bfredl")
            }

            if (labels.includes('filetype')) {
              reviewers.push("clason")
              reviewers.push("gpanders")
            }

            if (labels.includes('gui')) {
              reviewers.push("glacambre")
              reviewers.push("smolck")
            }

            if (labels.includes('lsp')) {
              reviewers.push("mfussenegger")
              reviewers.push("mjlbach")
            }

            if (labels.includes('treesitter')) {
              reviewers.push("bfredl")
              reviewers.push("vigoux")
            }

            if (labels.includes('typo')) {
              reviewers.push("dundargoc")
            }

            if (labels.includes('ui')) {
              reviewers.push("bfredl")
            }

            if (labels.includes('vim-patch')) {
              reviewers.push("janlazo")
              reviewers.push("seandewar")
              reviewers.push("zeertzjq")
            }

            // Remove person that opened the PR since they can't review themselves
            const pr_opener = pr_data.data.user.login
            const index = reviewers.indexOf(pr_opener)
            if (index > -1) {
              reviewers.splice(index, 1)
            }

            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              reviewers: reviewers
            });
