name: "Test Security"
on:
  pull_request_target:
jobs:
  test-security:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: ./test.sh
